# Generated by Django 5.0.1 on 2024-02-11 19:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AccountApp", "0002_user_date_joined_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
    ]
