# Generated by Django 5.0.1 on 2024-02-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DashboardApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="stock_status",
            field=models.IntegerField(),
        ),
    ]
