# Generated by Django 5.0.1 on 2024-02-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DashboardApp", "0002_alter_item_stock_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="available_stock",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="stock_status",
            field=models.FloatField(),
        ),
    ]
