# Generated by Django 5.0.1 on 2024-02-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DashboardApp", "0003_alter_item_available_stock_alter_item_stock_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(related_name="items", to="DashboardApp.tag"),
        ),
    ]
