# Generated by Django 5.0.1 on 2024-02-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DashboardApp", "0004_alter_item_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
